#server.port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOSTNAME}:5432/subscriptions
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non-contextual-creation: true
  kafka:
    jaas:
      enabled: false
    properties:
      sasl:
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
      linger:
        ms: 100
    consumer:
      bootstrap-servers: ${KAFKA_HOSTNAME}:9092
      group-id: subscriptions_internal
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: ${KAFKA_HOSTNAME}:9092

# Adidas Kafka Configuration
adidas:
  kafka:
    securityManager:
      url: http://${KAFKA_HOSTNAME}
    error:
      retry:
        interval: 100 # Default value in ms
        attempts: 2
    topics:
      - name: create_subscription
        num-partitions: 1
        replication-factor: 1
      - name: create_subscription_response
        num-partitions: 1
        replication-factor: 1
      - name: welcome_email
        num-partitions: 1
        replication-factor: 1